FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y doxygen git python3 python3-pip && \
    apt-get clean

# Pre-install Jenkins plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

USER jenkins
