version: '3.8'

services:
  jenkins:
    image: custom-jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./Jenkinsfile:/workspace/Jenkinsfile
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_data:
